### PR TITLE
[FEAT] Relative path to profiles

### LINKED ISSUE #31: [FEAT]:  Allow a relative path for the Profiles folder
### Description of the unfavorable solution

The current settings expects Profile Path to be an absolute path to somewhere on the computer.  This doesn't mesh well with the Obsidian folders being shared to other computers.  

### Describe the feature you would like to have

I want the path to be my relative to my obsidian vault as something like ..\Profiles.  This way both can be under a folder which is automatically synced to the cloud.

### Additional context

This of course will only work if all the vaults in question are at the same relative path on the computer.  But without such an adaptation, I think this plugin is only viable on single computer vaults, or on a series of computers that have vaults all on the same absolute path.

### PR DESCRIPTION
**Pull request by 4Source**
## Related Issues
Fixes #31 

## Checklist before requesting a review
- [x] I have followed the guidelines in our Contributing document
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My code fixes the feature discussed in [Related Issues](#related-issues)

### CODE REVIEW

**Comment by 4Source** [comment]
@abaljeu could you Test it? 

Here are the plugin files: 
[settings-profiles.zip](https://github.com/4Source/settings-profiles-obsidian-plugin/files/14318881/settings-profiles.zip)

**Comment by abaljeu** [comment]
I did get the setting to work.  I also tested on multiple devices and with a dropbox link, but unsurprisingly this was not working.  My CSS snippet edit got overwritten by a previous version.  I feel your plugin therefore is not viable for my context (2 vaults, 3 machines).  I understand that's difficult to support, especially with a young plugin, and possibly might not ever be workable.  Thanks anyway!
Alan ***@***.***
 

    On Saturday, February 17, 2024 at 08:11:26 a.m. EST, 4Source ***@***.***> wrote:  
 
 


@abaljeu could you Test it?

Here are the plugin files: (
settings-profiles.zip

**Comment by 4Source** [comment]
Have you Community plugin enabled in your profiles? Because currently this plugin needs to be updated in each profile and needs to be saved. If you don't do that you switch to a profile with an older version and it overrides the plugin with the old version. You can check this happens for you in the community plugins tab. 

I think it should be possible to use this plugin with your setup. There just needs to be some more work put into it. As you said the plugin is still pretty young.

**Comment by abaljeu** [comment]
i dont know what this means.On Feb 18, 2024, at 03:58, 4Source ***@***.***> wrote:﻿
Have you Community plugin enabled in your profiles? Because currently this plugin needs to be updated in each profile and needs to be saved. If you don't do that you switch to a profile with an older version and it overrides the plugin with the old version. You can check this happens for you in the community plugins tab.
I think it should be possible to use this plugin with your setup. There just needs to be some more work put into it. As you said the plugin is still pretty young.

**Comment by 4Source** [comment]
image

- When you go to the Settings Tab of this plugin *(1.)*.
- Than you can modify the Settings of a profile by Clicking on the 'Options' Button *(2.)* or you also see the window when creating a new profile.
- In the "Profile Settings" you can toggle on or off what you like to Synchronize with this profile. "Community Plugins" *(3.)*
Setting when turned on Synchronizes the settings made in the "Community plugins" from Obsidian but also copies the files from the plugins and with that there current installed version *(4.)*. 
- Because of that when you switch to another profile where the new version is not installed the plugin don't support the relative path feature anymore you need to install it for each profile.
- Also a thing to mention the Settings of the "Settings profiles" plugin didn't get Synchronized for the profiles so you can and need to configure it in each vault separately.
image

**Pull request merged**
